### ISSUE TITLE
Pathing to the generated css file doesn't work in subdirectories.

### ISSUE THREAD

**Issue by Amormzee** [jsBoot/gulp-docco#1]
if the following gulp configuration is used:

```
    gulp.src("./src/**/*.coffee")
      .pipe(docco())
      .pipe(gulp.dest('./docs'));
```

The docco.css file is output to docs and the HTML files are output to a directory structure that is mirroring the src one.  For example if a coffee file is in src/core/test.coffee the resulting HTML file would be in docs/core/test.html.

Inside that HTML file the CSS link to docco.css is assuming that a docco.css file exists in the current directory.

**Comment by dmp42** [comment]
I see.
I need a few days to look into this, as I'm currently relocating.

Thanks for the report!

**Comment by dmp42** [comment]
Back on this - sorry for the delay.

Looking at that: https://github.com/jashkenas/docco/pull/236

I wonder what is the right thing to do now. Generate a flat output (like docco) w/o the docco "bug" , or keep generating an output that reflects the original tree and fix the stylesheet paths.

What's your take?

**Comment by dmp42** [comment]
Still generates a tree reflecting the original source, and has correct path to css files.

The root gulpfile tests that. If you have a scenario where paths are still broken, please say so.

This is still missing inter-document navigation, though, but that's another story.
