### ISSUE TITLE
docco.css permissions: not world readable

### ISSUE THREAD

**Issue by backspaces** [jsBoot/gulp-docco#6]
The docco.css permissions need to be world readable:
    -rw-r-----  1 Home  staff   9.6K Jul  9 21:26 docco.css

**Comment by backspaces** [comment]
Similarly, the public/fonts/ and public/stylesheets/ files need to be world readable.

Without this, localhost & file:// browser access may fail with odd html layouts.

**Comment by backspaces** [comment]
Oops.  I did a clean install of node/npm and used the project version of gulp to build the docs and now seems to be world readable.

.. i.e. node_modules/gulp/bin/gulp.js docs seems to work.

I seem to be fighting with node/npm and loosing!  Let me get back to you after more exploration.

**Comment by dmp42** [comment]
Happy you tamed it :-)
